const CONNECTION_ENV = Object.freeze({
  ollama: ['OLLAMA_BASE_URL'],
  open_webui: ['OPEN_WEBUI_URL'],
  litellm: ['LITELLM_BASE_URL', 'LITELLM_MASTER_KEY'],
  openhands: ['OPENHANDS_URL', 'OPENHANDS_API_KEY'],
  aider: ['AIDER_ENABLED'],
  browser_use: ['BROWSER_USE_ENABLED'],
  langgraph: ['LANGGRAPH_ENABLED'],
  autogen: ['AUTOGEN_ENABLED'],
  crewai: ['CREWAI_ENABLED'],
  qdrant: ['QDRANT_URL', 'QDRANT_API_KEY'],
  chromadb: ['CHROMA_URL'],
  mimo: ['MIMO_API_KEY', 'MIMO_BASE_URL'],
  ornith: ['ORNITH_API_KEY', 'ORNITH_BASE_URL'],
  n8n: ['N8N_WEBHOOK_URL', 'N8N_API_KEY'],
  make: ['MAKE_WEBHOOK_URL'],
  zapier: ['ZAPIER_WEBHOOK_URL'],
  github_actions: ['GITHUB_TOKEN', 'GITHUB_REPO'],
  google_workspace: ['GOOGLE_REFRESH_TOKEN', 'GMAIL_REFRESH_TOKEN'],
  slack: ['SLACK_BOT_TOKEN', 'SLACK_WEBHOOK_URL'],
});

const AUTOMATION_INTEGRATIONS = Object.freeze([
  {
    id: 'ollama',
    name: 'Ollama',
    category: 'local-model-runtime',
    mode: 'local-first',
    description: 'Runs open-weight models locally behind an OpenAI-like local HTTP API. Best first unlimited-ish runtime on your Windows PC.',
    safeActions: ['local_chat', 'local_summarize', 'local_code_review', 'local_embedding_plan'],
    blockedActions: ['expose_public_without_auth', 'store_secrets_in_prompts', 'run_untrusted_models_with_filesystem_access'],
    routeHints: ['ollama', 'local model', 'local llm', 'qwen', 'llama', 'mistral', 'gemma'],
  },
  {
    id: 'open_webui',
    name: 'Open WebUI',
    category: 'local-ai-interface',
    mode: 'local-dashboard',
    description: 'Open local interface for chatting with multiple local or routed models. Useful as a home base for the assistant team.',
    safeActions: ['open_local_chat_ui', 'manage_local_prompts', 'connect_ollama'],
    blockedActions: ['publish_without_auth', 'connect_to_public_internet_without_review'],
    routeHints: ['open webui', 'webui', 'local dashboard'],
  },
  {
    id: 'litellm',
    name: 'LiteLLM',
    category: 'model-router',
    mode: 'router',
    description: 'Unified OpenAI-compatible proxy/router for local and cloud models with budgets and fallbacks.',
    safeActions: ['route_model_call', 'set_budget', 'fallback_between_models'],
    blockedActions: ['log_secrets', 'unbounded_spend', 'public_proxy_without_auth'],
    routeHints: ['litellm', 'model router', 'fallback model', 'proxy'],
  },
  {
    id: 'openhands',
    name: 'OpenHands',
    category: 'developer-agent',
    mode: 'sandbox-required',
    description: 'Open-source software engineering agent that can work in a sandboxed development environment.',
    safeActions: ['create_branch_plan', 'draft_code_changes', 'run_tests_in_sandbox', 'open_pr_draft'],
    blockedActions: ['edit_real_pc_without_bridge', 'merge_pr_without_approval', 'deploy_without_approval', 'access_secrets'],
    routeHints: ['openhands', 'opendevin', 'software agent', 'coding agent'],
  },
  {
    id: 'aider',
    name: 'Aider',
    category: 'developer-agent',
    mode: 'repo-local-review',
    description: 'Open-source command-line coding assistant for editing repos with git-aware review.',
    safeActions: ['propose_patch', 'run_local_tests', 'commit_to_feature_branch'],
    blockedActions: ['commit_to_main', 'push_without_review', 'edit_secrets'],
    routeHints: ['aider', 'repo edit', 'local coding'],
  },
  {
    id: 'browser_use',
    name: 'browser-use',
    category: 'browser-automation',
    mode: 'sandbox-required',
    description: 'Open-source browser automation layer for agents. Use only in an isolated browser profile/container.',
    safeActions: ['browse_public_web', 'fill_test_forms', 'collect_research'],
    blockedActions: ['enter_passwords', 'submit_forms_without_approval', 'purchase', 'send_messages_without_approval'],
    routeHints: ['browser-use', 'browser use', 'browser automation', 'web agent'],
  },
  {
    id: 'langgraph',
    name: 'LangGraph',
    category: 'agent-orchestration',
    mode: 'workflow-engine',
    description: 'Graph-based agent orchestration for durable multi-step workflows and stateful agents.',
    safeActions: ['design_agent_graph', 'run_mock_workflow', 'checkpoint_state'],
    blockedActions: ['loop_without_budget', 'tool_execution_without_policy'],
    routeHints: ['langgraph', 'agent graph', 'stateful agent'],
  },
  {
    id: 'autogen',
    name: 'AutoGen',
    category: 'multi-agent-framework',
    mode: 'workflow-engine',
    description: 'Open multi-agent framework for team-style reasoning and tool-use experiments.',
    safeActions: ['simulate_agent_team', 'create_review_loop', 'mock_tool_use'],
    blockedActions: ['unbounded_agent_chat', 'tool_execution_without_policy'],
    routeHints: ['autogen', 'multi agent', 'agent team'],
  },
  {
    id: 'crewai',
    name: 'CrewAI',
    category: 'multi-agent-framework',
    mode: 'workflow-engine',
    description: 'Role-based multi-agent framework for task crews and business/school workflow plans.',
    safeActions: ['create_crew_plan', 'assign_roles', 'draft_outputs'],
    blockedActions: ['auto_execute_external_actions', 'send_without_approval'],
    routeHints: ['crewai', 'crew ai', 'crew', 'agents'],
  },
  {
    id: 'qdrant',
    name: 'Qdrant',
    category: 'memory-vector-db',
    mode: 'local-or-cloud-memory',
    description: 'Vector database for long-term retrieval memory over your notes, code, and project docs.',
    safeActions: ['store_embeddings', 'retrieve_context', 'index_vault'],
    blockedActions: ['index_private_data_without_consent', 'public_memory_without_auth'],
    routeHints: ['qdrant', 'vector db', 'semantic memory'],
  },
  {
    id: 'chromadb',
    name: 'ChromaDB',
    category: 'memory-vector-db',
    mode: 'local-memory',
    description: 'Local vector database option for private memory and retrieval-augmented workflows.',
    safeActions: ['local_memory_index', 'retrieve_context'],
    blockedActions: ['index_secrets', 'public_memory_without_auth'],
    routeHints: ['chromadb', 'chroma', 'local memory'],
  },
  {
    id: 'mimo',
    name: 'Mimo',
    category: 'learning',
    mode: 'scaffolded',
    description: 'Turns tasks into guided lessons, quizzes, and practice steps. Does not edit repos or run tools.',
    safeActions: ['generate_learning_plan', 'generate_quiz', 'explain_code'],
    blockedActions: ['edit_repo', 'send_email', 'deploy', 'delete_files'],
    routeHints: ['mimo', 'lesson', 'learn', 'quiz', 'teach'],
  },
  {
    id: 'ornith',
    name: 'Ornith 1.0',
    category: 'experimental-frontier-harness',
    mode: 'sandbox-required',
    description: 'Experimental Frontier US model/harness system. Treated as an agent-harness builder/evaluator, not a general webhook tool.',
    safeActions: ['create_harness_plan', 'create_eval_plan', 'run_mock_harness', 'propose_agent_loop'],
    blockedActions: ['control_real_desktop', 'access_secrets', 'train_on_private_data_without_approval', 'execute_unreviewed_code', 'disable_logging'],
    routeHints: ['ornith', 'ornith 1.0', 'frontier us', 'harness', 'model harness'],
  },
  {
    id: 'n8n',
    name: 'n8n',
    category: 'workflow-automation',
    mode: 'webhook-preview',
    description: 'Open workflow automation option for review-first webhook payloads.',
    safeActions: ['preview_webhook_payload', 'queue_manual_webhook'],
    blockedActions: ['fire_webhook_without_approval', 'bulk_modify_drive', 'bulk_email_send'],
    routeHints: ['n8n', 'workflow', 'webhook'],
  },
  {
    id: 'make',
    name: 'Make',
    category: 'workflow-automation',
    mode: 'webhook-preview',
    description: 'Visual automation platform target for reviewed webhook payloads.',
    safeActions: ['preview_webhook_payload'],
    blockedActions: ['fire_webhook_without_approval', 'unreviewed_bulk_action'],
    routeHints: ['make.com', 'make', 'scenario'],
  },
  {
    id: 'zapier',
    name: 'Zapier',
    category: 'workflow-automation',
    mode: 'webhook-preview',
    description: 'No-code automation target for reviewed webhook payloads.',
    safeActions: ['preview_webhook_payload'],
    blockedActions: ['fire_webhook_without_approval', 'unreviewed_bulk_action'],
    routeHints: ['zapier', 'zap'],
  },
  {
    id: 'github_actions',
    name: 'GitHub Actions',
    category: 'developer-automation',
    mode: 'review-first',
    description: 'Runs CI and scheduled repo tasks only through reviewed workflow files and PRs.',
    safeActions: ['draft_workflow', 'inspect_ci', 'create_issue'],
    blockedActions: ['merge_pr_without_approval', 'deploy_without_approval', 'write_secret_to_repo'],
    routeHints: ['github actions', 'ci', 'workflow'],
  },
  {
    id: 'google_workspace',
    name: 'Google Workspace',
    category: 'school-productivity',
    mode: 'approval-required',
    description: 'Gmail, Calendar, Drive, Docs, Slides, Sheets, Forms, Tasks, and Contacts. Reads and drafts first; writes need approval.',
    safeActions: ['read_summary', 'create_draft', 'propose_calendar_event', 'propose_drive_reorg'],
    blockedActions: ['send_email_without_approval', 'delete_calendar_event_without_approval', 'bulk_drive_move_without_approval'],
    routeHints: ['gmail', 'calendar', 'drive', 'docs', 'slides', 'sheets', 'forms', 'tasks', 'contacts'],
  },
  {
    id: 'slack',
    name: 'Slack',
    category: 'team-automation',
    mode: 'draft-first',
    description: 'Band Council and team reminders, delegation summaries, and draft announcements.',
    safeActions: ['draft_message', 'summarize_channel', 'create_reminder_plan'],
    blockedActions: ['post_without_approval', 'dm_without_approval'],
    routeHints: ['slack', 'channel', 'delegation'],
  },
]);

export function listAutomationIntegrations(env = {}) {
  return AUTOMATION_INTEGRATIONS.map((integration) => ({
    ...integration,
    connected: getConnectionKeys(integration.id).some((key) => Boolean(env[key])),
    requiredEnv: getConnectionKeys(integration.id),
  }));
}

export function getAutomationIntegration(id, env = {}) {
  return listAutomationIntegrations(env).find((integration) => integration.id === id) || null;
}

export function routeAutomationTask(task = '', env = {}) {
  const lower = String(task || '').toLowerCase();
  const integrations = listAutomationIntegrations(env);
  const matched = integrations.find((integration) => integration.routeHints.some((hint) => lower.includes(hint)));
  const selected = matched || integrations.find((integration) => integration.id === 'ollama');
  return {
    ok: true,
    selected: selected?.id || 'chief_of_staff',
    integration: selected || null,
    execute: false,
    requiresApproval: true,
    nextStep: selected
      ? `Create a reviewed ${selected.name} plan/payload. Do not execute until Copeland approves.`
      : 'Create a normal Chief of Staff plan.',
  };
}

function getConnectionKeys(id) {
  return CONNECTION_ENV[id] || [];
}
