export function renderCommandCenterHtml() {
  return `<!doctype html>
<html lang="en">
<head>
  <meta charset="utf-8">
  <meta name="viewport" content="width=device-width,initial-scale=1,viewport-fit=cover">
  <meta name="theme-color" content="#f7fbff">
  <title>CopelandOS</title>
  <style>
    :root{color-scheme:light;--bg:#f7fbff;--text:#16232e;--muted:#607789;--soft:#8da1af;--accent:#2c8ef2;--accent2:#8b7cf6;--good:#1ea872;--warn:#b7791f;--bad:#de4d62;--line:rgba(74,129,174,.18);--glass:rgba(255,255,255,.62);--shadow:0 28px 85px rgba(64,101,132,.18)}
    *{box-sizing:border-box}html{scroll-behavior:smooth}body{margin:0;min-height:100vh;overflow-x:hidden;color:var(--text);font-family:Inter,ui-sans-serif,system-ui,-apple-system,Segoe UI,sans-serif;background:radial-gradient(circle at 18% -8%,rgba(111,196,255,.38),transparent 31rem),radial-gradient(circle at 88% 10%,rgba(162,145,255,.28),transparent 29rem),radial-gradient(circle at 42% 100%,rgba(123,247,218,.18),transparent 34rem),linear-gradient(135deg,#fbfdff 0%,#edf8ff 42%,#faf7ff 100%)}
    body:before{content:"";position:fixed;inset:0;pointer-events:none;opacity:.52;background-image:radial-gradient(circle at 22% 22%,rgba(44,142,242,.16) 0 1px,transparent 2px),radial-gradient(circle at 78% 44%,rgba(139,124,246,.14) 0 1px,transparent 2px),linear-gradient(115deg,transparent 0 46%,rgba(44,142,242,.08) 47%,transparent 49%);background-size:72px 72px,96px 96px,160px 160px;mask-image:linear-gradient(to bottom,black 0%,black 62%,transparent 100%)}
    body:after{content:"";position:fixed;inset:8vh 5vw auto auto;width:min(42vw,520px);height:min(42vw,520px);pointer-events:none;border-radius:50%;background:conic-gradient(from 120deg,transparent,rgba(44,142,242,.15),transparent 36%,rgba(139,124,246,.12),transparent 70%),radial-gradient(circle,transparent 52%,rgba(44,142,242,.14) 53%,transparent 55%);opacity:.68;animation:drift 18s ease-in-out infinite alternate}@keyframes drift{from{transform:translate3d(0,0,0) rotate(-4deg)}to{transform:translate3d(-4vw,4vh,0) rotate(6deg)}}
    main{position:relative;z-index:1;width:min(1180px,calc(100% - 24px));margin:auto;padding:18px 0 110px}.top{position:sticky;top:10px;z-index:10;margin:0 0 16px;padding:12px;border:1px solid rgba(255,255,255,.68);border-radius:28px;background:rgba(255,255,255,.58);backdrop-filter:blur(28px) saturate(1.2);box-shadow:0 18px 60px rgba(65,105,140,.14)}
    .brand{display:flex;align-items:center;justify-content:space-between;gap:12px}.brand-left{display:flex;gap:12px;align-items:center}.mark{width:36px;aspect-ratio:1;border-radius:42% 58% 48% 52%;border:1px solid rgba(44,142,242,.28);background:radial-gradient(circle at 35% 28%,rgba(255,255,255,.95),rgba(133,214,255,.42) 28%,transparent 56%),conic-gradient(from 180deg,rgba(44,142,242,.38),rgba(139,124,246,.24),rgba(120,255,219,.28),rgba(44,142,242,.38));box-shadow:0 12px 32px rgba(44,142,242,.16)}
    h1{margin:0;font-size:20px;letter-spacing:.1em}.subline{color:var(--muted);font:10px ui-monospace,monospace;letter-spacing:.16em;text-transform:uppercase}.tabs{display:flex;gap:8px;overflow-x:auto;-webkit-overflow-scrolling:touch;padding-top:12px}.tab,button,a.button{border:1px solid rgba(44,142,242,.18);border-radius:999px;background:rgba(255,255,255,.52);color:#38566a;padding:10px 13px;cursor:pointer;font-weight:760;text-decoration:none;touch-action:manipulation;white-space:nowrap}.tab:active,.tab:focus,button.primary,a.primary{background:linear-gradient(135deg,var(--accent),var(--accent2));color:white;border-color:transparent;box-shadow:0 16px 34px rgba(44,142,242,.22)}
    .section{scroll-margin-top:120px;margin-bottom:18px}.grid{display:grid;grid-template-columns:repeat(2,minmax(0,1fr));gap:14px}.triple{display:grid;grid-template-columns:1.3fr .7fr;gap:14px}.panel{position:relative;overflow:hidden;border:1px solid rgba(255,255,255,.72);border-radius:30px;background:linear-gradient(150deg,rgba(255,255,255,.80),rgba(255,255,255,.40)),radial-gradient(circle at 12% 0%,rgba(44,142,242,.13),transparent 22rem);box-shadow:var(--shadow);backdrop-filter:blur(28px) saturate(1.28)}.panel:before{content:"";position:absolute;inset:0;background:linear-gradient(135deg,rgba(255,255,255,.95),transparent 22%),linear-gradient(90deg,transparent,rgba(44,142,242,.18),transparent);opacity:.5;pointer-events:none}.panel>*{position:relative;z-index:1}.panel-head{display:flex;justify-content:space-between;gap:12px;align-items:start;padding:18px 18px 0}.title{font:750 12px ui-monospace,monospace;letter-spacing:.08em;text-transform:uppercase}.sub{color:var(--muted);font-size:12px;margin-top:4px;line-height:1.45}.badge,.pill{border:1px solid rgba(44,142,242,.18);border-radius:999px;background:rgba(255,255,255,.48);color:var(--muted);padding:5px 8px;font:10px ui-monospace,monospace;text-transform:uppercase;white-space:nowrap}.ok{color:var(--good)!important;border-color:rgba(30,168,114,.28)!important}.warn{color:var(--warn)!important;border-color:rgba(183,121,31,.28)!important}.bad{color:var(--bad)!important;border-color:rgba(222,77,98,.28)!important}
    .hero{min-height:390px;padding:24px;display:grid;grid-template-columns:1fr .8fr;gap:20px;align-items:center}.hero h2{font-size:clamp(42px,7vw,78px);line-height:.92;letter-spacing:-.075em;margin:0 0 16px}.hero p{color:var(--muted);line-height:1.65;max-width:62ch}.lens{min-height:300px;display:grid;place-items:center;position:relative;perspective:900px}.shape{width:clamp(210px,26vw,310px);aspect-ratio:1;position:relative;border-radius:34% 66% 57% 43%;background:radial-gradient(circle at 40% 32%,rgba(255,255,255,.96),rgba(134,218,255,.34) 24%,transparent 44%),conic-gradient(from 160deg,rgba(44,142,242,.22),rgba(139,124,246,.18),rgba(121,255,222,.18),rgba(44,142,242,.22));filter:drop-shadow(0 35px 60px rgba(44,142,242,.18));transform:rotateX(58deg) rotateZ(-18deg)}.shape:before,.shape:after{content:"";position:absolute;border-radius:inherit;border:1px solid rgba(44,142,242,.26);inset:-4%;animation:spin 36s linear infinite}.shape:after{inset:18%;border-color:rgba(139,124,246,.26);animation:spinBack 28s linear infinite}@keyframes spin{to{transform:rotate(360deg)}}@keyframes spinBack{to{transform:rotate(-360deg)}}
    .form{padding:16px;display:grid;gap:11px}label{font-size:11px;color:var(--muted);display:grid;gap:6px}input,textarea,select{width:100%;border:1px solid rgba(255,255,255,.70);border-radius:18px;background:rgba(255,255,255,.50);color:var(--text);padding:12px 14px;font:16px inherit;backdrop-filter:blur(22px) saturate(1.2)}textarea{min-height:110px;resize:vertical}.row{display:grid;grid-template-columns:1fr 1fr;gap:10px}.log{min-height:210px;max-height:420px;overflow:auto;border:1px solid rgba(255,255,255,.70);border-radius:22px;background:rgba(255,255,255,.50);padding:12px;font:12px ui-monospace,monospace;white-space:pre-wrap;color:#38566a}.pills{display:flex;flex-wrap:wrap;gap:8px}.code{font:12px ui-monospace,monospace;word-break:break-all;color:#38566a;background:rgba(255,255,255,.50);border:1px solid rgba(255,255,255,.70);padding:10px;border-radius:18px}.steps{color:var(--muted);font-size:13px;line-height:1.6}.steps b{color:var(--text)}@media(max-width:780px){main{width:min(100% - 12px,1180px);padding-top:6px}.grid,.triple,.hero,.row{grid-template-columns:1fr}.panel{border-radius:24px}.top{top:6px}.tab{font-size:13px;padding:10px 11px}.hero{padding:18px 16px}.form{padding:14px}.shape{transform:rotateX(52deg) rotateZ(-18deg) scale(.9)}}
  </style>
</head>
<body>
<main>
  <div class="top"><div class="brand"><div class="brand-left"><span class="mark" aria-hidden="true"></span><div><h1>COPELANDOS</h1><div class="subline">Flow interface</div></div></div><button id="refresh-status" type="button">Refresh</button></div><nav class="tabs" aria-label="Sections"><a class="tab" href="#home">Home</a><a class="tab" href="#capture">Capture</a><a class="tab" href="#google">Google</a><a class="tab" href="#memory">Memory</a><a class="tab" href="#logs">Activity</a></nav></div>

  <section id="home" class="section"><article class="panel hero"><div><span class="badge ok">local preview ready</span><h2>Think clearly.<br>Act safely.</h2><p>Capture ideas, route tasks, draft email, and save notes with clear review boundaries. Nothing sensitive is assumed connected until the Worker confirms it.</p><div class="pills" id="signal-pills"><span class="pill">status loads here</span></div></div><div class="lens"><div class="shape" aria-hidden="true"></div></div></article><div class="grid"><article class="panel"><div class="panel-head"><div><div class="title">Task router</div><div class="sub">Routes work to learning, email, calendar, drive, memory, or coding prompts.</div></div><span class="badge ok">safe</span></div><form class="form" id="route-form"><label>Task<textarea id="route-task" placeholder="What should CopelandOS figure out?"></textarea></label><button class="primary" type="submit">Route task</button></form></article><article class="panel"><div class="panel-head"><div><div class="title">Quick links</div><div class="sub">Direct Worker URLs.</div></div></div><div class="form"><a class="button primary" href="/console">Open interface</a><a class="button" href="/api/status">API status</a><a class="button" href="/api/health">API health</a></div></article></div></section>

  <section id="capture" class="section"><div class="grid"><article class="panel"><div class="panel-head"><div><div class="title">Idea capture</div><div class="sub">Works from dashboard or phone shortcuts.</div></div><span class="badge ok">safe</span></div><form class="form" id="idea-form"><label>Idea<textarea id="idea-text" placeholder="Tell CopelandOS what to remember or plan…"></textarea></label><div class="row"><label>Source<select id="idea-source"><option>dashboard</option><option>ios-shortcuts</option><option>siri</option><option>mobile-web</option></select></label><label>Urgency<select id="idea-urgency"><option>medium</option><option>low</option><option>high</option></select></label></div><button class="primary" type="submit">Capture idea</button></form></article><article class="panel"><div class="panel-head"><div><div class="title">Phone shortcut setup</div><div class="sub">Use the GET URL version first. It is easiest on Apple Shortcuts.</div></div><button id="copy-shortcut" type="button">Copy URL</button></div><div class="form"><div class="code" id="shortcut-url">https://copelandos.copelandbaker20.workers.dev/api/capture/idea?text=SHORTCUT_TEXT&amp;source=ios-shortcuts&amp;urgency=medium&amp;tags=ios,shortcut</div><div class="steps"><b>Actions:</b> Ask for Input → URL Encode Provided Input → Text URL → Get Contents of URL → Show Notification.</div><label>Test text<input id="shortcut-test" value="Test capture from Apple Shortcuts"></label><button id="test-get-capture" class="primary" type="button">Test GET capture now</button></div></article></div></section>

  <section id="google" class="section"><div class="grid"><article class="panel"><div class="panel-head"><div><div class="title">Gmail drafts</div><div class="sub">Triage inbox, label/archive, and create drafts. Sending requires explicit approval.</div></div><span class="badge warn">approval</span></div><form class="form" id="mail-form"><label>To<input id="mail-to" autocomplete="email" placeholder="person@example.com"></label><label>Subject<input id="mail-subject" placeholder="Draft subject"></label><label>Body<textarea id="mail-body" placeholder="Write the draft here…"></textarea></label><button class="primary" type="submit">Create Gmail draft</button></form></article><article class="panel"><div class="panel-head"><div><div class="title">Google setup</div><div class="sub">Use Gmail auth first; broader auth can be added separately.</div></div></div><div class="form"><div class="code">Redirect URI: https://copelandos.copelandbaker20.workers.dev/api/auth/callback</div><div class="code">Required secrets: GOOGLE_CLIENT_ID, GOOGLE_CLIENT_SECRET, GOOGLE_REFRESH_TOKEN</div><a class="button primary" href="/api/auth/gmail">Connect Gmail</a><a class="button" href="/api/auth/google">Connect broader Google when route exists</a></div></article></div></section>

  <section id="memory" class="section"><article class="panel"><div class="panel-head"><div><div class="title">Vault note</div><div class="sub">GitHub vault write if configured; otherwise safe preview.</div></div><span class="badge ok">memory</span></div><form class="form" id="note-form"><label>Title<input id="note-title" placeholder="Note title"></label><div class="row"><label>Folder<select id="note-folder"><option>Inbox</option><option>Projects</option><option>School</option><option>BandCouncil</option><option>Music</option><option>Research</option><option>Decisions</option><option>Ideas</option></select></label><label>Agent<input id="note-agent" value="copelandos"></label></div><label>Content<textarea id="note-content" placeholder="Markdown note content…"></textarea></label><button class="primary" type="submit">Save / preview note</button></form></article></section>

  <section id="logs" class="section"><article class="panel"><div class="panel-head"><div><div class="title">Activity</div><div class="sub">Everything returns here so you can see what worked.</div></div></div><div class="form"><div class="log" id="log">CopelandOS loaded.\n</div></div></article></section>
</main>
<script>
(() => {
  const $ = id => document.getElementById(id);
  const logBox = $('log');
  const log = (label, data) => { if (!logBox) return; const text = typeof data === 'string' ? data : JSON.stringify(data, null, 2); logBox.textContent += '\n[' + label + '] ' + text + '\n'; logBox.scrollTop = logBox.scrollHeight; };
  async function api(path, options = {}) { const r = await fetch(path, options); const text = await r.text(); let data = {}; try { data = text ? JSON.parse(text) : {}; } catch { throw new Error('Non-JSON response (' + r.status + ')'); } if (!r.ok) { const e = new Error(data.error || data.message || 'HTTP ' + r.status); e.data = data; throw e; } return data; }
  function safeListen(id, event, fn) { const el = $(id); if (el) el.addEventListener(event, fn); }
  async function loadStatus(){ try { const status = await api('/api/status'); const modules = status.modules || {}; const pills = $('signal-pills'); if (pills) pills.innerHTML = [ ['Worker','ok',true], ['Router','ok',modules.hermes && modules.hermes.connected], ['Gmail','warn',modules.gmail && modules.gmail.connected], ['Vault','ok',modules.vault && modules.vault.connected] ].map(([name, cls, on]) => '<span class="pill ' + (on ? cls : '') + '">' + name + ': ' + (on ? 'connected' : 'not connected') + '</span>').join(''); log('status', status.modules); } catch(e){ log('status-error', e.message); } }
  safeListen('idea-form','submit', async e => { e.preventDefault(); try { const data = await api('/api/capture/idea', { method:'POST', headers:{'Content-Type':'application/json'}, body: JSON.stringify({ text:$('idea-text').value, source:$('idea-source').value, urgency:$('idea-urgency').value, tags:['interface'] }) }); $('idea-text').value=''; log('idea captured', data); location.hash = 'logs'; } catch(err){ log('idea error', err.data || err.message); location.hash = 'logs'; } });
  safeListen('route-form','submit', async e => { e.preventDefault(); try { const data = await api('/api/hermes/route', { method:'POST', headers:{'Content-Type':'application/json'}, body: JSON.stringify({ task:$('route-task').value, source:'interface' }) }); log('route', data); location.hash = 'logs'; } catch(err){ log('route error', err.data || err.message); location.hash = 'logs'; } });
  safeListen('mail-form','submit', async e => { e.preventDefault(); try { const data = await api('/api/email/draft', { method:'POST', headers:{'Content-Type':'application/json'}, body: JSON.stringify({ to:$('mail-to').value, subject:$('mail-subject').value, body:$('mail-body').value, confirmed:true }) }); log('gmail draft', data); location.hash = 'logs'; } catch(err){ log('gmail error', err.data || err.message); location.hash = 'logs'; } });
  safeListen('note-form','submit', async e => { e.preventDefault(); try { const data = await api('/api/obsidian/save', { method:'POST', headers:{'Content-Type':'application/json'}, body: JSON.stringify({ title:$('note-title').value, folder:$('note-folder').value, content:$('note-content').value, agent:$('note-agent').value, tags:['interface'] }) }); log('vault note', data); location.hash = 'logs'; } catch(err){ log('vault error', err.data || err.message); location.hash = 'logs'; } });
  function shortcutUrl(text){ return location.origin + '/api/capture/idea?text=' + encodeURIComponent(text || 'SHORTCUT_TEXT') + '&source=ios-shortcuts&urgency=medium&tags=ios,shortcut'; }
  safeListen('copy-shortcut','click', async () => { const url = shortcutUrl('SHORTCUT_TEXT'); try { await navigator.clipboard.writeText(url); log('copied', url); } catch { log('copy', url); } });
  safeListen('test-get-capture','click', async () => { try { const data = await api('/api/capture/idea?text=' + encodeURIComponent($('shortcut-test').value) + '&source=dashboard-test&urgency=medium&tags=test'); log('get capture', data); location.hash = 'logs'; } catch(err){ log('get capture error', err.data || err.message); location.hash = 'logs'; } });
  safeListen('refresh-status','click', loadStatus);
  loadStatus();
})();
</script>
</body>
</html>`;
}
